### PR TITLE
Nb locale

### PR DESCRIPTION
**Pull request by snake66**
Here's the updated locale file for Norwegian Bokmål (nb).

### CODE REVIEW

**Comment by snake66** [comment]
These errors does not seem to be related to my change...

**Comment by simi** [comment]
Thanks! CI fail is not related to your changes. Is there any chance to squash commits into one @snake66 ?

**Comment by snake66** [comment]
Sure, is there a way to do that in the same pr, or should I just make a new one again?

**Comment by simi** [comment]
Sure it is. Just squash it into one commit and force push to same branch. This PR will be refreshed automatically.

**Comment by snake66** [comment]
Um... not really sure that was right... Anyways. Should be mergable to master.

**Comment by simi** [comment]
Almost there. Can you try this?

1. git fetch --all
2. git rebase upstream/master (change upstream to refinery remote name)
3. force push

**Comment by snake66** [comment]
Now then :)

**Comment by simi** [comment]
Awesome!

**Pull request merged**
